variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "ssh_key_name" {}
variable "vpc_id" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "mysql_name" {}
variable "mysql_username" {}
variable "mysql_password" {}